client_a_uplink_in :: FromDevice();
client_a_uplink_out :: ToDevice();
client_a_clients_in :: FromDevice();
client_a_clients_out :: ToDevice();
client_a_uplink_r0_s0_match0 :: IPClassifier(dst net 192.168.1.0/24, -);
client_a_uplink_in -> client_a_uplink_r0_s0_match0;
client_a_uplink_r0_s0_dec_ttl :: DecIPTTL();
client_a_uplink_r0_s0_match0[0] -> client_a_uplink_r0_s0_dec_ttl;
client_a_uplink_r0_s0_dec_ttl -> client_a_clients_out;
client_a_uplink_r0_s0_fallback :: Null;
client_a_uplink_r0_s0_match0[1] -> client_a_uplink_r0_s0_fallback;
client_a_uplink_r0_s0_fallback -> Discard;
client_a_clients_r0_s0_match0 :: IPClassifier(dst udp port 67, -);
client_a_clients_in -> client_a_clients_r0_s0_match0;
client_a_clients_r0_s0_match1 :: IPClassifier(ether dst ffff.ffff.ffff, -);
client_a_clients_r0_s0_match0[0] -> client_a_clients_r0_s0_match1;
client_a_clients_r0_s0_match1[0] -> client_a_uplink_out;
client_a_clients_r0_s0_fallback :: Null;
client_a_clients_r0_s0_match0[1] -> client_a_clients_r0_s0_fallback;
client_a_clients_r0_s0_match1[1] -> client_a_clients_r0_s0_fallback;
client_a_clients_r0_s1_match0 :: IPClassifier(dst net 192.168.1.0/24, -);
client_a_clients_r0_s0_fallback -> client_a_clients_r0_s1_match0;
client_a_clients_r0_s1_dec_ttl :: DecIPTTL();
client_a_clients_r0_s1_match0[1] -> client_a_clients_r0_s1_dec_ttl;
client_a_clients_r0_s1_dec_ttl -> client_a_uplink_out;
client_a_clients_r0_s1_fallback :: Null;
client_a_clients_r0_s1_match0[0] -> client_a_clients_r0_s1_fallback;
client_a_clients_r0_s1_fallback -> Discard;
client_b_uplink_in :: FromDevice();
client_b_uplink_out :: ToDevice();
client_b_clients_in :: FromDevice();
client_b_clients_out :: ToDevice();
client_b_uplink_r0_s0_match0 :: IPClassifier(dst net 192.168.2.0/24, -);
client_b_uplink_in -> client_b_uplink_r0_s0_match0;
client_b_uplink_r0_s0_dec_ttl :: DecIPTTL();
client_b_uplink_r0_s0_match0[0] -> client_b_uplink_r0_s0_dec_ttl;
client_b_uplink_r0_s0_dec_ttl -> client_b_clients_out;
client_b_uplink_r0_s0_fallback :: Null;
client_b_uplink_r0_s0_match0[1] -> client_b_uplink_r0_s0_fallback;
client_b_uplink_r0_s0_fallback -> Discard;
client_b_clients_r0_s0_match0 :: IPClassifier(dst udp port 67, -);
client_b_clients_in -> client_b_clients_r0_s0_match0;
client_b_clients_r0_s0_match1 :: IPClassifier(ether dst ffff.ffff.ffff, -);
client_b_clients_r0_s0_match0[0] -> client_b_clients_r0_s0_match1;
client_b_clients_r0_s0_match1[0] -> client_b_uplink_out;
client_b_clients_r0_s0_fallback :: Null;
client_b_clients_r0_s0_match0[1] -> client_b_clients_r0_s0_fallback;
client_b_clients_r0_s0_match1[1] -> client_b_clients_r0_s0_fallback;
client_b_clients_r0_s1_match0 :: IPClassifier(dst net 192.168.2.0/24, -);
client_b_clients_r0_s0_fallback -> client_b_clients_r0_s1_match0;
client_b_clients_r0_s1_dec_ttl :: DecIPTTL();
client_b_clients_r0_s1_match0[1] -> client_b_clients_r0_s1_dec_ttl;
client_b_clients_r0_s1_dec_ttl -> client_b_uplink_out;
client_b_clients_r0_s1_fallback :: Null;
client_b_clients_r0_s1_match0[0] -> client_b_clients_r0_s1_fallback;
client_b_clients_r0_s1_fallback -> Discard;
naas_client_a_port_in :: FromDevice();
naas_client_a_port_out :: ToDevice();
naas_client_b_port_in :: FromDevice();
naas_client_b_port_out :: ToDevice();
naas_server_port_in :: FromDevice();
naas_server_port_out :: ToDevice();
naas_client_a_port_r0_s0_match0 :: IPClassifier(dst net 10.0.0.0/24, -);
naas_client_a_port_in -> naas_client_a_port_r0_s0_match0;
naas_client_a_port_r0_s0_match0[0] -> naas_server_port_out;
naas_client_a_port_r0_s0_fallback :: Null;
naas_client_a_port_r0_s0_match0[1] -> naas_client_a_port_r0_s0_fallback;
naas_client_a_port_r0_s0_fallback -> Discard;
naas_client_b_port_r0_s0_match0 :: IPClassifier(dst net 10.0.0.0/24, -);
naas_client_b_port_in -> naas_client_b_port_r0_s0_match0;
naas_client_b_port_r0_s0_match0[0] -> naas_server_port_out;
naas_client_b_port_r0_s0_fallback :: Null;
naas_client_b_port_r0_s0_match0[1] -> naas_client_b_port_r0_s0_fallback;
naas_client_b_port_r0_s0_fallback -> Discard;
naas_server_port_r0_s0_match0 :: IPClassifier(dst net 192.168.1.0/24, -);
naas_server_port_in -> naas_server_port_r0_s0_match0;
naas_server_port_r0_s0_match0[0] -> naas_client_a_port_out;
naas_server_port_r0_s0_fallback :: Null;
naas_server_port_r0_s0_match0[1] -> naas_server_port_r0_s0_fallback;
naas_server_port_r1_s0_match0 :: IPClassifier(dst net 192.168.2.0/24, -);
naas_server_port_r0_s0_fallback -> naas_server_port_r1_s0_match0;
naas_server_port_r1_s0_match0[0] -> naas_client_b_port_out;
naas_server_port_r1_s0_fallback :: Null;
naas_server_port_r1_s0_match0[1] -> naas_server_port_r1_s0_fallback;
naas_server_port_r1_s0_fallback -> Discard;
server_naas_link_in :: FromDevice();
server_naas_link_out :: ToDevice();
server_servers_in :: FromDevice();
server_servers_out :: ToDevice();
server_naas_link_r0_s0_match0 :: IPClassifier(dst net 10.0.0.0/24, -);
server_naas_link_in -> server_naas_link_r0_s0_match0;
server_naas_link_r0_s0_dec_ttl :: DecIPTTL();
server_naas_link_r0_s0_match0[0] -> server_naas_link_r0_s0_dec_ttl;
server_naas_link_r0_s0_dec_ttl -> server_servers_out;
server_naas_link_r0_s0_fallback :: Null;
server_naas_link_r0_s0_match0[1] -> server_naas_link_r0_s0_fallback;
server_naas_link_r0_s1_match0 :: IPClassifier(src net 192.168.1.0/24, -);
server_naas_link_r0_s0_fallback -> server_naas_link_r0_s1_match0;
server_naas_link_r0_s1_match0[0] -> server_servers_out;
server_naas_link_r0_s1_fallback :: Null;
server_naas_link_r0_s1_match0[1] -> server_naas_link_r0_s1_fallback;
server_naas_link_r0_s2_match0 :: IPClassifier(src net 192.168.2.0/24, -);
server_naas_link_r0_s1_fallback -> server_naas_link_r0_s2_match0;
server_naas_link_r0_s2_match0[0] -> server_servers_out;
server_naas_link_r0_s2_fallback :: Null;
server_naas_link_r0_s2_match0[1] -> server_naas_link_r0_s2_fallback;
server_naas_link_r0_s2_fallback -> Discard;
server_servers_r0_s0_match0 :: IPClassifier(dst net 192.168.1.0/24, -);
server_servers_in -> server_servers_r0_s0_match0;
server_servers_r0_s0_dec_ttl :: DecIPTTL();
server_servers_r0_s0_match0[0] -> server_servers_r0_s0_dec_ttl;
server_servers_r0_s0_dec_ttl -> server_naas_link_out;
server_servers_r0_s0_fallback :: Null;
server_servers_r0_s0_match0[1] -> server_servers_r0_s0_fallback;
server_servers_r0_s1_match0 :: IPClassifier(dst net 192.168.2.0/24, -);
server_servers_r0_s0_fallback -> server_servers_r0_s1_match0;
server_servers_r0_s1_dec_ttl :: DecIPTTL();
server_servers_r0_s1_match0[0] -> server_servers_r0_s1_dec_ttl;
server_servers_r0_s1_dec_ttl -> server_naas_link_out;
server_servers_r0_s1_fallback :: Null;
server_servers_r0_s1_match0[1] -> server_servers_r0_s1_fallback;
server_servers_r0_s1_fallback -> Discard;
client_a_uplink_out -> naas_client_a_port_in;
naas_client_a_port_out -> client_a_uplink_in;
client_b_uplink_out -> naas_client_b_port_in;
naas_client_b_port_out -> client_b_uplink_in;
naas_server_port_out -> server_naas_link_in;
server_naas_link_out -> naas_server_port_in;
