client_b_uplink_in :: FromDevice();
client_b_uplink_out :: ToDevice();
client_b_clients_in :: FromDevice();
client_b_clients_out :: ToDevice();
client_b_uplink_r0_s0_match0 :: IPClassifier(dst net 192.168.2.0/24, -);
client_b_uplink_in -> client_b_uplink_r0_s0_match0;
client_b_uplink_r0_s0_dec_ttl :: DecIPTTL();
client_b_uplink_r0_s0_match0[0] -> client_b_uplink_r0_s0_dec_ttl;
client_b_uplink_r0_s0_dec_ttl -> client_b_clients_out;
client_b_uplink_r0_s0_fallback :: Null;
client_b_uplink_r0_s0_match0[1] -> client_b_uplink_r0_s0_fallback;
client_b_uplink_r0_s0_fallback -> Discard;
client_b_clients_r0_s0_match0 :: IPClassifier(dst udp port 67, -);
client_b_clients_in -> client_b_clients_r0_s0_match0;
client_b_clients_r0_s0_match1 :: IPClassifier(ether dst ffff.ffff.ffff, -);
client_b_clients_r0_s0_match0[0] -> client_b_clients_r0_s0_match1;
client_b_clients_r0_s0_match1[0] -> client_b_uplink_out;
client_b_clients_r0_s0_fallback :: Null;
client_b_clients_r0_s0_match0[1] -> client_b_clients_r0_s0_fallback;
client_b_clients_r0_s0_match1[1] -> client_b_clients_r0_s0_fallback;
client_b_clients_r0_s1_match0 :: IPClassifier(dst net 192.168.2.0/24, -);
client_b_clients_r0_s0_fallback -> client_b_clients_r0_s1_match0;
client_b_clients_r0_s1_dec_ttl :: DecIPTTL();
client_b_clients_r0_s1_match0[1] -> client_b_clients_r0_s1_dec_ttl;
client_b_clients_r0_s1_dec_ttl -> client_b_uplink_out;
client_b_clients_r0_s1_fallback :: Null;
client_b_clients_r0_s1_match0[0] -> client_b_clients_r0_s1_fallback;
client_b_clients_r0_s1_fallback -> Discard;