client_a_uplink_in :: FromDevice();
client_a_uplink_out :: ToDevice();
client_a_clients_in :: FromDevice();
client_a_clients_out :: ToDevice();
client_a_uplink_r0_s0_match0 :: IPClassifier(dst net 192.168.1.0/24, -);
client_a_uplink_in -> client_a_uplink_r0_s0_match0;
client_a_uplink_r0_s0_dec_ttl :: DecIPTTL();
client_a_uplink_r0_s0_match0[0] -> client_a_uplink_r0_s0_dec_ttl;
client_a_uplink_r0_s0_dec_ttl -> client_a_clients_out;
client_a_uplink_r0_s0_fallback :: Null;
client_a_uplink_r0_s0_match0[1] -> client_a_uplink_r0_s0_fallback;
client_a_uplink_r0_s0_fallback -> Discard;
client_a_clients_r0_s0_match0 :: IPClassifier(dst udp port 67, -);
client_a_clients_in -> client_a_clients_r0_s0_match0;
client_a_clients_r0_s0_match1 :: IPClassifier(ether dst ffff.ffff.ffff, -);
client_a_clients_r0_s0_match0[0] -> client_a_clients_r0_s0_match1;
client_a_clients_r0_s0_match1[0] -> client_a_uplink_out;
client_a_clients_r0_s0_fallback :: Null;
client_a_clients_r0_s0_match0[1] -> client_a_clients_r0_s0_fallback;
client_a_clients_r0_s0_match1[1] -> client_a_clients_r0_s0_fallback;
client_a_clients_r0_s1_match0 :: IPClassifier(dst net 192.168.1.0/24, -);
client_a_clients_r0_s0_fallback -> client_a_clients_r0_s1_match0;
client_a_clients_r0_s1_dec_ttl :: DecIPTTL();
client_a_clients_r0_s1_match0[1] -> client_a_clients_r0_s1_dec_ttl;
client_a_clients_r0_s1_dec_ttl -> client_a_uplink_out;
client_a_clients_r0_s1_fallback :: Null;
client_a_clients_r0_s1_match0[0] -> client_a_clients_r0_s1_fallback;
client_a_clients_r0_s1_fallback -> Discard;