naas_client_a_port_in :: FromDevice();
naas_client_a_port_out :: ToDevice();
naas_client_b_port_in :: FromDevice();
naas_client_b_port_out :: ToDevice();
naas_server_port_in :: FromDevice();
naas_server_port_out :: ToDevice();
naas_client_a_port_r0_s0_match0 :: IPClassifier(dst net 10.0.0.0/24, -);
naas_client_a_port_in -> naas_client_a_port_r0_s0_match0;
naas_client_a_port_r0_s0_match0[0] -> naas_server_port_out;
naas_client_a_port_r0_s0_fallback :: Null;
naas_client_a_port_r0_s0_match0[1] -> naas_client_a_port_r0_s0_fallback;
naas_client_a_port_r0_s0_fallback -> Discard;
naas_client_b_port_r0_s0_match0 :: IPClassifier(dst net 10.0.0.0/24, -);
naas_client_b_port_in -> naas_client_b_port_r0_s0_match0;
naas_client_b_port_r0_s0_match0[0] -> naas_server_port_out;
naas_client_b_port_r0_s0_fallback :: Null;
naas_client_b_port_r0_s0_match0[1] -> naas_client_b_port_r0_s0_fallback;
naas_client_b_port_r0_s0_fallback -> Discard;
naas_server_port_r0_s0_match0 :: IPClassifier(dst net 192.168.1.0/24, -);
naas_server_port_in -> naas_server_port_r0_s0_match0;
naas_server_port_r0_s0_match0[0] -> naas_client_a_port_out;
naas_server_port_r0_s0_fallback :: Null;
naas_server_port_r0_s0_match0[1] -> naas_server_port_r0_s0_fallback;
naas_server_port_r1_s0_match0 :: IPClassifier(dst net 192.168.2.0/24, -);
naas_server_port_r0_s0_fallback -> naas_server_port_r1_s0_match0;
naas_server_port_r1_s0_match0[0] -> naas_client_b_port_out;
naas_server_port_r1_s0_fallback :: Null;
naas_server_port_r1_s0_match0[1] -> naas_server_port_r1_s0_fallback;
naas_server_port_r1_s0_fallback -> Discard;