server_naas_link_in :: FromDevice();
server_naas_link_out :: ToDevice();
server_servers_in :: FromDevice();
server_servers_out :: ToDevice();
server_naas_link_r0_s0_match0 :: IPClassifier(dst net 10.0.0.0/24, -);
server_naas_link_in -> server_naas_link_r0_s0_match0;
server_naas_link_r0_s0_dec_ttl :: DecIPTTL();
server_naas_link_r0_s0_match0[0] -> server_naas_link_r0_s0_dec_ttl;
server_naas_link_r0_s0_dec_ttl -> server_servers_out;
server_naas_link_r0_s0_fallback :: Null;
server_naas_link_r0_s0_match0[1] -> server_naas_link_r0_s0_fallback;
server_naas_link_r0_s1_match0 :: IPClassifier(src net 192.168.1.0/24, -);
server_naas_link_r0_s0_fallback -> server_naas_link_r0_s1_match0;
server_naas_link_r0_s1_match0[0] -> server_servers_out;
server_naas_link_r0_s1_fallback :: Null;
server_naas_link_r0_s1_match0[1] -> server_naas_link_r0_s1_fallback;
server_naas_link_r0_s2_match0 :: IPClassifier(src net 192.168.2.0/24, -);
server_naas_link_r0_s1_fallback -> server_naas_link_r0_s2_match0;
server_naas_link_r0_s2_match0[0] -> server_servers_out;
server_naas_link_r0_s2_fallback :: Null;
server_naas_link_r0_s2_match0[1] -> server_naas_link_r0_s2_fallback;
server_naas_link_r0_s2_fallback -> Discard;
server_servers_r0_s0_match0 :: IPClassifier(dst net 192.168.1.0/24, -);
server_servers_in -> server_servers_r0_s0_match0;
server_servers_r0_s0_dec_ttl :: DecIPTTL();
server_servers_r0_s0_match0[0] -> server_servers_r0_s0_dec_ttl;
server_servers_r0_s0_dec_ttl -> server_naas_link_out;
server_servers_r0_s0_fallback :: Null;
server_servers_r0_s0_match0[1] -> server_servers_r0_s0_fallback;
server_servers_r0_s1_match0 :: IPClassifier(dst net 192.168.2.0/24, -);
server_servers_r0_s0_fallback -> server_servers_r0_s1_match0;
server_servers_r0_s1_dec_ttl :: DecIPTTL();
server_servers_r0_s1_match0[0] -> server_servers_r0_s1_dec_ttl;
server_servers_r0_s1_dec_ttl -> server_naas_link_out;
server_servers_r0_s1_fallback :: Null;
server_servers_r0_s1_match0[1] -> server_servers_r0_s1_fallback;
server_servers_r0_s1_fallback -> Discard;